### PR TITLE
LRCI-1485 Add a method to get a list of random online jenkins nodes

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-1485

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Ended up not putting it in LoadBalancerUtil, but just put it in parallel to JenkinsResultsParserUtil.getSlaves() which is what we call from the beanshell to get the dist node list. 

Additionally, should we consider again renaming things from slave to agent? I know it was rejected by BChan last time, but maybe it's something we could refactor at some point.

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
I made a few changes, can you test this out? Go ahead and forward if it works..
https://github.com/kenjiheigel/liferay-portal/pull/646

**Pull request closed without merging**
