### PR TITLE
LRQA-41190 Add class for PortalReleaseJob to handle test class groups

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-41190

@pyoo47 - One thing that might be weird about this is that I chose not to make a "GitWorkingDirectoryFactory" because we are using the constructor directly within "liferay-jenkins-ee".
https://github.com/liferay/liferay-jenkins-ee/blob/aed5ac9/commands/build-common.xml#L7901

If you think we can make both public constructors and a factory, then I can change this.  But let me know what you think.

Thanks!

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
cc @lesliewong92

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/59337

@michaelhashimoto Please see my changes in the pull request. Regarding the GitWorkingDirectory factory issue, I'd like to move to using only a factory class. We can implement support for both so we don't break anything while we transition the direct constructor calls to factory method calls.

**Pull request closed without merging**
