### PR TITLE
LRCI-4036 Run each project in a separate downstream build

### PR DESCRIPTION
**Pull request by brittneyq**
https://liferay.atlassian.net/browse/LRCI-4036

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@brittneyq In the future, you should put JenkinsResultsParser changes into its own pull request.

**Comment by brittneyq** [comment]
@pyoo47 oh my bad. I'll send the changes separately. I might need to change a minor thing.

**Comment by pyoo47** [comment]
ci:stop

**Pull request closed without merging**
