### PR TITLE
LRQA-33727 Remove os specific logic for poshi file scanning

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-33727

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/50322

**Pull request closed without merging**
