### PR TITLE
POSHI-107 Move PropsUtil into 'poshi-core' to maintain history

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/POSHI-107

I resent it to clean up the comments, Peter's pull was merged here:
https://github.com/brianchandotcom/liferay-portal/pull/94449

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
