### PR TITLE
LRCI-1155 Check full module name when checking modified modules

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-1155

Tested here: https://github.com/yichenroy/liferay-portal/pull/351

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:relevant

Flaky functional test?
 ```
    [exec]     BUILD FAILED: Element is present at "//html[contains(@class,'lfr-spa-loading')]"
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/Navigator.macro[_gotoPage]:7
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/Navigator.macro[gotoPage]:131
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/Upgrade.macro[viewUpgrade]:2646
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/upgrades/PortalSmokeUpgrade.testcase[ViewPortalSmokeArchive621021]:180
```

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
