### PR TITLE
LRCI-3710 Change how the Jenkins objects are initialized to clean up object relationships

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://liferay.atlassian.net/browse/LRCI-3710

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward:force

**Comment by pyoo47** [comment]
ci:forward:force

**Pull request closed without merging**
