### PR TITLE
LRQA-37014 Include delay time info to jenkins report

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-37014

Looks like this (average wait time and longest wait time shown on top section):
https://test-1-15.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/839/jenkins-report.html

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/54294

**Comment by pyoo47** [comment]
@michaelhashimoto @yichenroy Please see my changes in the push to BChan

**Pull request closed without merging**
