### PR TITLE
LRQA-34833 Delete github/bundles in portal-license-jdk8 during test-tear-down

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-34833

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:reopen

**Comment by yichenroy** [comment]
ci:stop

**Comment by yichenroy** [comment]
ci:retest
rebase and retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/51431

**Pull request closed without merging**
