### PR TITLE
LRQA-43864 Avoid StackOverflow when property used is unset

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-43864

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@michaelhashimoto I think there might still be a problem here?

**Comment by michaelhashimoto** [comment]
I see it, I sent an SF fix here:
https://github.com/pyoo47/liferay-portal/pull/807

**Pull request closed without merging**
