### PR TITLE
LRCI-1190 Implement sendSlackNotification()

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRCI-1190

Please publish after merging

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:forward

**Comment by jpince** [comment]
@pyoo47 is there a reason why you're implementing in portal instead of using the existing infrastructure in jenkins?

**Comment by jpince** [comment]
See https://issues.liferay.com/browse/LRCI-1150

**Comment by pyoo47** [comment]
@jpince I'm implementing this here because it will make it easier to implement the feature for upstream source-format failures. This logic should have been implemented here in the first place. If you look at the ant implementation, most of the logic is implemented in beanshell. When this is merged, this new method will be used to replace the logic in the macrodef.

**Comment by pyoo47** [comment]
ci:test:relevant:nocompile

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:reopen

**Pull request closed without merging**
