### PR TITLE
LRQA-40590 Add jsf-jdk8 batch

### PR DESCRIPTION
**Pull request by kevin-yen**
https://issues.liferay.com/browse/LRQA-40590

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by kevin-yen** [comment]
@pyoo47 @jpince I'm going to resend this after I make some changes

**Pull request closed without merging**
