### PR TITLE
LRCI-1323 Refactor naming of SpiraTestCaseObjects

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1323

Based off of requests made by BChan here:
https://github.com/brianchandotcom/liferay-portal/pull/88857

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
