### PR TITLE
LRCI-635,649 Generate ci:test:stable github comment within ci:test:relevant|Include stable implicitly in relevant (resend)

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-635
https://issues.liferay.com/browse/LRCI-649

Tested here:
master(1): https://github.com/yichenroy/liferay-portal/pull/180#issuecomment-542421381
master(2): https://github.com/yichenroy/liferay-portal/pull/178#issuecomment-542421471
7.0.x:         https://github.com/yichenroy/liferay-portal-ee/pull/113#issuecomment-542423241

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/79595

**Comment by pyoo47** [comment]
ci:stop

**Pull request closed without merging**
