### PR TITLE
LRQA-33105 Add portal-license-jdk8 batch test

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-33105

The last commit:
https://github.com/yichenroy/liferay-portal/commit/535cc1309491c27b7e563b0760e2a4832d9c5846
is there to initiate the git.diff comparison in release-tool-ee for the pull request tester, remove this commit before sending it to BChan. 

*****Edit:
The following needs to be merged first (sets release.tool.dir property the batch test needs):
https://github.com/pyoo47/liferay-jenkins-ee/pull/528

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:stop

**Comment by yichenroy** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by yichenroy** [comment]
ci:stop
rebasing and retesting

**Comment by yichenroy** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/51384#issuecomment-327366725

**Pull request closed without merging**
