### PR TITLE
POSHI-88 Make 'BaseWebDriverImpl.executeJavaScript' more flexible

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-88

@Tim-Cao

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:stop

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
I renamed the exception and sent it to myself for forwarding to BChan
https://github.com/pyoo47/liferay-portal/pull/1385

**Pull request closed without merging**
