### PR TITLE
LRQA-38970 Create a custom Jenkins Report for Git Bisect Tool

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-38970

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Made some changes and sent back to Hashi for testing
https://github.com/michaelhashimoto/liferay-portal/pull/1259

**Pull request closed without merging**
