### PR TITLE
LRCI-597 Expire resource connections if they have been stale for too long

### PR DESCRIPTION
**Pull request by michaelhashimoto**
http://issues.liferay.com/browse/LRCI-597

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/77884

@michaelhashimoto Please see my changes in the pull request.

**Pull request closed without merging**
