### PR TITLE
LRQA-42243 Split setupWorkspace() into separate methods, and add support for caching jenkins branches

### PR DESCRIPTION
**Pull request by michaelhashimoto**
http://issues.liferay.com/browse/LRQA-42243

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@michaelhashimoto Can you rebase off of https://github.com/brianchandotcom/liferay-portal/pull/62494 and resend?

**Comment by michaelhashimoto** [comment]
Rebased, and repushed here:
https://github.com/pyoo47/liferay-portal/pull/757

**Pull request closed without merging**
