### PR TITLE
LRCI-1102 Only cache search results if there are some matches to the query

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1102

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan (using ci:forward)
https://github.com/pyoo47/liferay-portal/pull/1231

**Comment by pyoo47** [comment]
@yichentsai My first `ci:forward`

**Pull request closed without merging**
