### PR TITLE
LRQA-28179 Modify Poshi implementation to handle non-string variables

### PR DESCRIPTION
**Pull request by lesliewong92**
http://issues.liferay.com/browse/LRQA-28179

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:stop stuck on dist job

**Comment by lesliewong92** [comment]
ci:retest

**Comment by lesliewong92** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
http://issues.liferay.com/browse/LRQA-28179

**Pull request closed without merging**
