### PR TITLE
LPS-104973 Implement Basic Authentication support in MirrorsGetTask

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LPS-104973

Please publish **MirrorsGetTask** after merging

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward

**Comment by lipusz** [comment]
Thank you, Peter for working on this! :+1:

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
