### PR TITLE
LRQA-42821 Fix sem ver and service builder batch test class group

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-42821

https://github.com/pyoo47/liferay-portal-ee/pull/389 (7.0.x backported properties only)

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/62066
https://github.com/brianchandotcom/liferay-portal-ee/pull/21324
https://github.com/brianchandotcom/liferay-portal-ee/pull/21325

**Pull request closed without merging**
