### PR TITLE
LRCI-1234 Allow Spira Test Case recording to happen in multiple threads 

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1234
https://issues.liferay.com/browse/LRCI-1241
https://issues.liferay.com/browse/LRCI-1226

Please publish after merging

@pyoo47 - After testing it out, I found a couple of places that we still needed to have synchronization.  I believe your fix did get rid of a lot of the synchronization though, thanks! :)

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
