### PR TITLE
LRQA-32500 Update pull request github comment to compare failures to upstream acceptance

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-32500

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by kenjiheigel** [comment]
Sample:
https://gist.github.com/kenjiheigel/5e28990e43d0cfbd5fb9706d6ff5e30e

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/50368

@kenjiheigel Please note my changes in the pull to BChan.

**Pull request closed without merging**
