### PR TITLE
master-qa-24997

### PR DESCRIPTION
**Pull request by kevin-yen**
https://issues.liferay.com/browse/LRQA-24997

### CODE REVIEW

**Comment by kevin-yen** [comment]
ci:stop

**Comment by kevin-yen** [comment]
This hasn't been tested yet

**Comment by kevin-yen** [comment]
Test ran https://test-1-7.liferay.com/job/test-jenkins-acceptance-pullrequest/6/ and it seems to work

**Comment by pyoo47** [comment]
ci:retest

**Comment by kevin-yen** [comment]
@pyoo47 It failed source formatting. I just fixed it now.

**Comment by pyoo47** [comment]
ci:retest

**Comment by kevin-yen** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/39527

**Pull request closed without merging**
