### PR TITLE
LRCI-1645 Fix for reinvocation bug

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-1645

All 10 out 10 test runs didn't run into the issue, console for the 3 latest runs:   
https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(7.0.x)/534/console
https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(7.0.x)/533/console
https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(7.0.x)/532/console

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
Rebased with the latest upstream, going to retest.

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:test:relevant:11e6081f96abb6bf299369519434c1eafa0658e3

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
