### PR TITLE
LRQA-32927 Changed TestResult.java to display part of stack trace for failed tests.

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-32927

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:reopen

**Comment by yichenroy** [comment]
ci:retest

**Comment by pyoo47** [comment]
@yichenroy The code changes here seems to have a much bigger effect than just resolving the issue described in the JIRA ticket. Did someone tell you that we needed to display the stack trace for all test failures?

**Comment by yichenroy** [comment]
The JIRA ticket had a link to 
https://github.com/pyoo47/liferay-portal/pull/330
where the expectation was to display what the error was for a test, and from the looks of Jason's comment in that pull request it seemed like having a little snippet from the beginning of the error stack trace would give more information.

Let me ask Jason about it to make sure.

**Comment by yichenroy** [comment]
I've asked Jason in which he replied:
"ideally, each failed test should display a stack trace snippet"

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/49475

**Pull request closed without merging**
