### PR TITLE
LRCI-2821 Remove irrelevant components displayed in ci:test:security routine

### PR DESCRIPTION
**Pull request by brittneyq**
https://issues.liferay.com/browse/LRCI-2821 

Tested [here](https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=1622923136).

### CODE REVIEW

**Comment by brittneyq** [comment]
`Caused by: java.net.UnknownHostException: mirrors-no-cache.lax.liferay.com`, unrelated to changes. Retesting.

**Comment by brittneyq** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
