### PR TITLE
LRQA-47128 Use test class group for subrepo pullrequest tests

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-47128

https://github.com/pyoo47/liferay-portal-ee/pull/550 (7.0.x)
https://github.com/pyoo47/liferay-portal-ee/pull/551 (7.1.x)

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/68794

**Pull request closed without merging**
