### PR TITLE
LRQA-46901 Fix inaccurate slave usage calculation

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-46901

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/68255

**Comment by pyoo47** [comment]
@lesliewong92 Can you look into the unit test failure?

**Comment by lesliewong92** [comment]
Fixed and resent at https://github.com/pyoo47/liferay-portal/pull/967

**Pull request closed without merging**
