### PR TITLE
LRCI-1167 Add custom properties to Spira results

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1167

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@michaelhashimoto I think you cherry-picked my first commit that had an SF issue. Replace that commit with the new one https://github.com/pyoo47/liferay-portal/commit/ba85648f5753918f3d803fc3763400bc38571929

**Comment by michaelhashimoto** [comment]
@pyoo47 - Oops, I'll redo the branch. Thanks!

**Pull request closed without merging**
