### PR TITLE
LRCI-3441 Add all required objects to create a build queue

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-3441

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
@michaelhashimoto I think the name, "javaJDK" sounds redundant.. I think it should be "javaVersion"

**Comment by michaelhashimoto** [comment]
@pyoo47 - I can make that update, I'll push up a fix.

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/130090

**Pull request closed without merging**
