### PR TITLE
POSHI-105 & POSHI-106 Remove old and unused dependencies/features

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-105
https://issues.liferay.com/browse/POSHI-106

Additional testing against these changes here: 
https://github.com/kenjiheigel/liferay-portal/pull/688#issuecomment-690974001

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:relevant

caught a top level with the incorrect system time. i offlined them and updated the thread

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
