### PR TITLE
LRCI-3345 Create a module to create objects & a module to create custom endpoints

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-3345

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@michaelhashimoto Are you aware that the changes in [this commit](https://github.com/pyoo47/liferay-portal/pull/2400/commits/6de0e3c0427af2153a6629c7eb7b65f126e70926) are reverted by [this commit](https://github.com/pyoo47/liferay-portal/pull/2400/commits/b36dd055d6d14c8f889585859bf18c3f729de4af)? Just making sure that was intended.

**Comment by pyoo47** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
@pyoo47 - It's okay, those are just place holders anyways.  Thanks!

**Pull request closed without merging**
