### PR TITLE
LRCI-3766 Add a simple project page

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://liferay.atlassian.net/browse/LRCI-3766

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:stable

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by michaelhashimoto** [comment]
ci:foward:force

**Comment by pyoo47** [comment]
ci:forward:force

**Pull request closed without merging**
