### PR TITLE
POSHI-128 Additionally catch InvalidSelectorException for invalid arguments in javascript methods

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-128

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
@kenjiheigel I tried reevaluating the most recent test result but it still failed.. Can you investigate? 

http://test-1-5/view/All/job/test-portal-evaluate-pullrequest/1/

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
