### PR TITLE
LRCI-1795 Get test case properties content from batch class groups

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1795

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:foward

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
