### PR TITLE
POSHI-92 Poshi cannot type some special characters on Safari

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-92

Tested here: https://github.com/kenjiheigel/liferay-portal/pull/671

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@kenjiheigel I had an idea to simplify this but I fear that it will cause a lot slowness. Can you take a look and let me know what you think? https://github.com/kenjiheigel/liferay-portal/pull/673

**Comment by pyoo47** [comment]
Closing this for now pending discussion on what is actually needed.

**Pull request closed without merging**
