### PR TITLE
LRCI-3346 Add base for a Jenkins Plugin called 'jenkins-plugins-events'

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-3346

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
Accidentally frowarded this before `relevant` was done. I manually aborted the  duplicate`relevant` build that got triggered.

**Comment by michaelhashimoto** [comment]
ci:forward:force

**Comment by michaelhashimoto** [comment]
ci:forward:force

**Pull request closed without merging**
