### PR TITLE
Stable Fix | Revert LPD-35730 Fix A non-localizabled field is disabled in journalArticle.spec.ts

### PR DESCRIPTION
**Pull request by pyoo47**
Reverting a commit to pass `stable`. The commit contained invalid Playwright tests. (See [comment in Slack](https://liferay.slack.com/archives/C19PWQ74J/p1725634827835649?thread_ts=1725624339.288059&cid=C19PWQ74J) for more details)

I've also added a couple of commits to fix some SF failures that were discovered while trying to forward this pull request.

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward:force

**Comment by petershin** [comment]
@pyoo47 - why is this commit needed: https://github.com/pyoo47/liferay-portal/pull/3379/commits/6caf4540c33b3b32ce7f7ae2bca32f9279f6c030

**Comment by pyoo47** [comment]
@petershin I don't really know why. Source Formatter made that change.

**Comment by pyoo47** [comment]
ci:forward:force

**Pull request closed without merging**
