### PR TITLE
LRQA-41603 Test class group logic for SemVer applies only to modules

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-41603

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by lesliewong92** [comment]
ci:stop

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/60149

**Pull request closed without merging**
