### PR TITLE
LRCI-40 Add support for the portal legacy repository in RCA Tool

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-40

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/69160

**Comment by michaelhashimoto** [comment]
ci:help

**Pull request closed without merging**
