### PR TITLE
LRCI-1349 Add test suite and test batches for oracle linux 6 & 7

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-1349

Tested here:
`orcllinux 6`: https://test-1-20.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8881/jenkins-report.html
`orcllinux 7`: https://test-1-20.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8873/jenkins-report.html

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
