### PR TITLE
POSHI-235 Add files for Poshi VSCode extension

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-235

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by pyoo47** [comment]
@kenjiheigel Can you take a look at the module structure test failure?

```
junit.framework.AssertionFailedError: Version must match the project version (1.0.0) modules/test/poshi/poshi-vscode/package.json
  at com.liferay.portal.modules.ModulesStructureTest._testJSONVersion(ModulesStructureTest.java:1541)
  at com.liferay.portal.modules.ModulesStructureTest.access$500(ModulesStructureTest.java:68)
  at com.liferay.portal.modules.ModulesStructureTest$2.preVisitDirectory(ModulesStructureTest.java:305)
  at com.liferay.portal.modules.ModulesStructureTest$2.preVisitDirectory(ModulesStructureTest.java:168)
  at java.nio.file.Files.walkFileTree(Files.java:2677)
  at java.nio.file.Files.walkFileTree(Files.java:2742)
  at com.liferay.portal.modules.ModulesStructureTest.testScanBuildScripts(ModulesStructureTest.java:166)
```

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
