### PR TITLE
POSHI-91 Update edge driver property | POSHI-93 Update WebDriver JavaScript methods

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-91
https://issues.liferay.com/browse/POSHI-93

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
@john-co, @Tim-Cao, @vicnate5 fyi

**Comment by john-co** [comment]
cc/ @zhangyan0701

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
