### PR TITLE
LRCI-4391 Dynamic jdk based on batch names

### PR DESCRIPTION
**Pull request by CharlotteFrancis**
https://liferay.atlassian.net/issues/LRCI-4391

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:stable

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by CharlotteFrancis** [comment]
ci:test:relevant

**Comment by CharlotteFrancis** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by CharlotteFrancis** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to myself with some minor changes
https://github.com/pyoo47/liferay-portal/pull/3404

**Pull request closed without merging**
