### PR TITLE
LRQA-43864 Avoid StackOverflow exceptions being thrown when getting properties

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-43864

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/63695

@michaelhashimoto I made a few more changes for error handling and to avoid other possible problems. Please see my changes in the pull request.

**Pull request closed without merging**
