### PR TITLE
LRQA-33088 Rename *_STRING into TOKEN_*

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-33088

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/49479

**Pull request closed without merging**
