### PR TITLE
LRCI-1253 Fix upstream acceptance URLs

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-1253

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
@kenjiheigel I aborted the relevant test since sf failed.

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant:nocompile

**Comment by pyoo47** [comment]
ci:test:relevant:nocompile

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
