### PR TITLE
LRQA-30625 Removed upstream-functional-tomcat80-mysql56-jdk8 target (7.0.x)

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-30625

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:open

**Comment by yichenroy** [comment]
ci:retest

**Comment by yichenroy** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/49514

**Pull request closed without merging**
