### PR TITLE
LRQA-33040 Add portal-startup-with-space-in-path-jdk8 batch test

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-33040

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:reopen

**Comment by yichenroy** [comment]
ci:retest

**Comment by yichenroy** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by yichenroy** [comment]
There is a "Communications Link Failure" that happens on jenkins but not on my local machine.
I sent myself a pull request and will do more testing there instead, will close this for now.

**Pull request closed without merging**
