### PR TITLE
LRQA-29185 Update poshi validation for errors involving comments

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-29185 

@pyoo, just making the validation less cryptic. We had an issue today where poshi validation failed, but we didn't know what caused it. There's more information in the ticket. I discussed this with Hashi briefly.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:stop

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
Missed an auto SF just now, good to go now.

**Comment by kenjiheigel** [comment]
ci:stop

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/44926

@kenjiheigel I made a tiny adjustment.

**Pull request closed without merging**
