### PR TITLE
LRQA-33092 Refactor failure message classes into its own package

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-33092

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
@yichenroy I don't think this will compile. Can you take another look at resend?

**Comment by pyoo47** [comment]
ci:stop

**Comment by yichenroy** [comment]
Ok, I will look into it an resend.

**Comment by yichenroy** [comment]
One of the base failure message classes was missing an import, it is fixed and the commit is squashed.
Will initiate retest.

**Comment by yichenroy** [comment]
ci:retest

**Comment by yichenroy** [comment]
ci:reopen

**Comment by yichenroy** [comment]
ci:open

**Comment by pyoo47** [comment]
ci:stop

**Pull request closed without merging**
