### PR TITLE
LRCI-503 Create failure message generator for validate-git-commit failure

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-503

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
I aborted the ci:test:relevant that was sent to the K8s cluster.

**Comment by pyoo47** [comment]
Sent back to Roy with a request..
https://github.com/yichenroy/liferay-portal/pull/159

**Pull request closed without merging**
