### PR TITLE
LRQA-39853 Stop any lingering geckodriver processes

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-39853

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@pyoo47, this will need to be backported to 7.0.x.

**Comment by kenjiheigel** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:reopen
service-builder-jdk8 is failing on upstream.

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/56845
https://github.com/brianchandotcom/liferay-portal-ee/pull/19799

**Pull request closed without merging**
