### PR TITLE
POSHI-89 Set a max of 2500 characters per exception in poshi-warning.xml

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/POSHI-89

Tested here:
https://github.com/yichenroy/liferay-portal/pull/438

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
