### PR TITLE
LRCI-4226 Add jenkins cohorts & jenkins masters to the UI

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://liferay.atlassian.net/browse/LRCI-4226

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:stable

**Comment by pyoo47** [comment]
ci:test:stable

**Comment by pyoo47** [comment]
ci:forward:force

**Pull request closed without merging**
