### PR TITLE
LRQA-39321 Add new SubrepositoryJob class to get information on subrepository pull requests

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-39321

@pyoo47 I have some questions/concerns about the changes I made here:
1. I added the method _getIncludedResourceURLs_ in order to get the list of URL's of a given glob. I didn't use the _findFiles_ method as I need to search for directories as well (in this case, searching for the testIntegration directory).
2. We currently use both _subrepo_ and _subrepository_. _subrepo_ is usually used as part of the property name, _subrepository_ is usually used for file names/variables/ant targets. I'm not sure if we should change one to the other?

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:help

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@lesliewong92 Merge conflict can you fix and resend?

**Comment by lesliewong92** [comment]
Resent. https://github.com/pyoo47/liferay-portal/pull/598

**Pull request closed without merging**
