### PR TITLE
LRCI-4149 Shift job definitions over to GraphQL instead of regular REST APIs

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://liferay.atlassian.net/browse/LRCI-4149

This is a continuation of this pull:
https://github.com/pyoo47/liferay-portal/pull/3160

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward:force

**Pull request closed without merging**
