### PR TITLE
LRCI-4031 Rename setup -> set_up & teardown -> tear_down

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://liferay.atlassian.net/browse/LRCI-4031

@brianchandotcom - This is in response to the slack message where you said:
> Can you rename setup.sh to set_up.sh and teardown.sh to tear_down.sh
> For https://github.com/brianchandotcom/liferay-portal/pull/146527

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:playwright:nocompile

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:playwright:nocompile

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward:force

**Pull request closed without merging**
