### PR TITLE
LRCI-1289 Add a custom field for file paths within Spira test cases

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRCI-1289

Please publish after merging

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:test:relevant:nocompile

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
