### PR TITLE
LRQA-36522 Allow upstream comparison logic to load results from a local file

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-36522

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
I've asked Kenji for some changes. He will resend.

**Comment by kenjiheigel** [comment]
Resent:
https://github.com/pyoo47/liferay-portal/pull/504

**Pull request closed without merging**
