### PR TITLE
LRQA-33040 portal startup with space in path

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-33040

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:retest

**Comment by yichenroy** [comment]
ci:stop

**Comment by yichenroy** [comment]
Will rebase with upstream and send again

**Comment by yichenroy** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/50029

**Pull request closed without merging**
