### PR TITLE
master-qa-41625

### PR DESCRIPTION
**Pull request by kiyoshilee**
https://issues.liferay.com/browse/LRQA-41625

### CODE REVIEW

**Comment by kiyoshilee** [comment]
@pyoo47 I can also do this through properties if you'd prefer. I didn't however want to add the extra dependency for something that maybe the factory can take care of instead. Let me know if you prefer this to be handled by properties though.

**Comment by kiyoshilee** [comment]
ci:test:sf

**Comment by kiyoshilee** [comment]
ci:test

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/60295

**Pull request closed without merging**
