### PR TITLE
LRCI-3403 Add batch client extension for Jethr0

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-3403

@pyoo47 - I tried to break down the required JSON entries one at a time to help clarify the purpose of each entry.  Please let me know if you have any questions about these changes.  Thanks!

Here's a simple representation of what I created with these objects:

**Task**
- String: name
- Integer: priority
- Picklist: type (downstreamJob, topLevelJob)

**Task Parameter**
- String: name
- String: value
- Task: relationship (oneToMany)

I also enabled the portlet & indexing for each field.

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
