### PR TITLE
LRQA-45817 Update DOM4J version for Jenkins Results Parser


### PR DESCRIPTION
**Pull request by kevin-yen**
https://issues.liferay.com/browse/LRQA-45817

### CODE REVIEW

**Comment by kevin-yen** [comment]
ci:test

**Comment by pyoo47** [comment]
@kevin-yen I just realized that the version of dom4j that you upgraded to requires JDK8. Let's talk and make sure this still works for ee-6.2.x where JDK7 is required.

**Comment by kevin-yen** [comment]
@pyoo47 I verified that issue on ee-6.2.x http://test-1-20/job/test-portal-acceptance-upstream(ee-6.2.x)/3 so I re-added the JDK 7 requirement lines in Gradle and changed the DOM4J version to 2.0.2 which still have generics support, security fixes, and support JDK 5+

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/66416

**Pull request closed without merging**
