### PR TITLE
LRCI-1958 Add SimpleBuild implementation

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-1958

Basically, I just want to use the Jenkins api to check if a job is finished running \(`Build.getResult()`\). If I use TopLevelBuild, it gets all the additional downstream information, which is unnecessary.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@kenjiheigel Instead of creating a handicapped Build class, I would rather move the logic in BaseBuild.getBuildJSONObject() to a new class/method JenkinsAPIUtil.getBuildJSONObject(buildURL, tree). You can take it a step further by creating another method, JenkinsAPIUtil.getBuildResult(buildURL).

**Comment by kenjiheigel** [comment]
Resent: 
https://github.com/pyoo47/liferay-portal/pull/1677

**Pull request closed without merging**
