### PR TITLE
LRQA-43448 Generate csv report for junit backend tests  (resend)

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-43448

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/63406

@yichenroy I think I found a better way implement the PortalGitRepositoryJob, see my commit in the pull request.

**Comment by pyoo47** [comment]
@yichenroy I also removed the changes to build-test.xml and test.properties. We should send them later to ee-6.1.x?, ee-6.1.30?, ee-6.2.x?, ee-6.2.10?, 7.0.x, 7.1.x and master after the jenkins results parser changes have been merged in.

**Pull request closed without merging**
