### PR TITLE
LRCI-1983, LRCI-2088, & LRCI-2089

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1983 - Import Testray results by Test Class instead of Test Method (Testray 1)
https://issues.liferay.com/browse/LRCI-2088 - Change testray case result status to Untested if it was not ran
https://issues.liferay.com/browse/LRCI-2089 - Send Testray attachments for QA Websites

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
