### PR TITLE
POSHI-120 Remove poshi property validation to simplify the process

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/POSHI-120

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
The CI failures look suspicious to me. @michaelhashimoto Can you take a look? If they are not related to this pull request, go ahead and reopen. Otherwise, resend.

**Pull request closed without merging**
