### PR TITLE
LRCI-4139  Relate GitPullRequest objects to Jobs upon creation for better tracking

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://liferay.atlassian.net/browse/LRCI-4139

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:stable

**Comment by pyoo47** [comment]
ci:forward:force

**Pull request closed without merging**
