### PR TITLE
LRCI-1529 Add a class to gather CI system data across the Jenkins masters

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRCI-1529

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
@kenjiheigel Now that this has happened twice I'm thinking that this is not some network issue. Any idea why this could be happening?

**Comment by pyoo47** [comment]
@kenjiheigel is working on a fix for the unit test failure. He will resend when it's ready.

**Comment by kenjiheigel** [comment]
Resent:
https://github.com/pyoo47/liferay-portal/pull/1423

**Pull request closed without merging**
