### PR TITLE
LRQA-32801 Add more prints to readable translation unit test failures

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-32801 

@pyoo47, couldn't figure out why the test failed in those recent pulls. I haven't seen it fail recently though. Adding in these prints to give more information in case it happens again.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:stop

Forgot to remove some temporary commits.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/liferay/liferay-portal/pull/2040

**Pull request closed without merging**
