### PR TITLE
POSHI-44 Fix missing Poshi Script validation messages

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-44

Resent from: https://github.com/pyoo47/com-liferay-poshi-runner/pull/307

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Sent back to Kenji to test my changes.
https://github.com/kenjiheigel/liferay-portal/pull/548

**Pull request closed without merging**
