### PR TITLE
LRQA-43898 Fix filepath for junit test csv report

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-43898

Tested a created jenkins-results-parser jar here: (ci:test and ci:test:relevant)
https://github.com/yichenroy/liferay-portal/pull/96

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:reopen

**Comment by pyoo47** [comment]
Made some changes and sent back to Roy for testing.
https://github.com/yichenroy/liferay-portal/pull/97

**Pull request closed without merging**
