### PR TITLE
LRQA-40590 Add jsf-jdk8 batch

### PR DESCRIPTION
**Pull request by kevin-yen**
https://issues.liferay.com/browse/LRQA-40590

### CODE REVIEW

**Comment by kevin-yen** [comment]
ci:test

**Comment by kevin-yen** [comment]
ci:test:sf

**Comment by kevin-yen** [comment]
ci:test:relevent

**Comment by kevin-yen** [comment]
https://github.com/pyoo47/liferay-portal/pull/669

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/59466

**Pull request closed without merging**
