### PR TITLE
LRCI-1188 Cache all created & found spira artifacts

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1188

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@michaelhashimoto Are you sure you want to use `Collections.singletonList()`? Just as a reminder, the List it returns is immutable.

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
