### PR TITLE
LRCI-1409 Add method to get the controller build

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1409

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@michaelhashimoto I'd fix this for you but I'm not sure what you're trying to do here, but I'm pretty sure this `if` statement can never be true:

```
		if ((controllerBuildURL == null) &&
			controllerBuildURL.matches("https?:\\/\\/.*")) {
```

**Comment by michaelhashimoto** [comment]
Fixed here:
https://github.com/pyoo47/liferay-portal/pull/1391

**Pull request closed without merging**
