### PR TITLE
LRQA-46901 Fix inaccurate slave usage calculation

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-46901

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test:

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/68415

**Comment by pyoo47** [comment]
@lesliewong92 Please see my changes in the pull request

**Pull request closed without merging**
