### PR TITLE
LRCI-973 Add postgresql 12.1 and sqlserver 2019 batches

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-973

@pyoo47 we may need to backport some of these commits to `7.0.x`, `7.1.x`, and `7.2.x` if they make sense.

Tested here:
`Functional batches`
https://test-1-20.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/8190/jenkins-report.html

`Modules integration`:
`postgresql 12.1`
https://test-1-20.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/8196/jenkins-report.html

`sqlserver 2019`
https://test-5-1.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/2646/jenkins-report.html

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:stable

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/85101

@yichenroy I commented on the pull request that this should not be backported anywhere since these new databases are for 7.3 only. If CNQA wants them for 7.2 and down, they can submit a new ticket.

**Pull request closed without merging**
