### PR TITLE
LRCI-1971 Add failure message generator for ClosedChannelException in batch job failures

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-1971 

@pyoo47, let me know if you want to change anything. The comment will look like this: https://gist.github.com/kenjiheigel/1dd00c0a1be05179dbfee12c4cfde976#gistcomment-3624715

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
