### PR TITLE
LRCI-3406 Add Spring Security configurations to the Spring Boot Application

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRCI-3406

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
I will forward this pull request manually.

**Comment by pyoo47** [comment]
Pushed to BChan

**Pull request closed without merging**
