### PR TITLE
LRCI-3131 Update com.liferay.jenkins.results.parser to 1.0.1105 in gradle-plugins-testray

### PR DESCRIPTION
**Pull request by michaelhashimoto**
http://issues.liferay.com/browse/LRCI-3131

@brianchandotcom - If this looks good can a new release be created? Let me know. Thanks!

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1257401_4269

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1387401_3250

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@michaelhashimoto I'm not seeing license-smoke on the flaky test report but that report doesn't show very many... Do you know if it's been flaky lately?

**Comment by michaelhashimoto** [comment]
@pyoo47 - I think for the flaky test report we only show JUnit Tests & Poshi Tests right now.  I don't think we track the flakiness of other batch types.

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
