### PR TITLE
LRCI-1147 Add ability to specify relevant global query

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-1147

Adding new query property that will be "AND" with old queries:
https://github.com/pyoo47/liferay-portal/pull/1243/commits/2a75b5f0d14a68831727a8aae9215376846c6742

cc @michaelhashimoto @kenjiheigel

Example: 
When I modified a file in `modules/apps/blogs`, I get this query:
`((portal.upstream != quarantine)) AND (((portal.upstream == true) AND ((testray.component.names ~ "Blogs") OR (testray.main.component.name ~ "Blogs"))))`

When no module is modified I get this query:
`((portal.upstream != quarantine)) AND ((false))`

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
will fix SF..

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward

**Comment by yichenroy** [comment]
@pyoo47 going to resend and take out the commit (the global property) Kenji already sent in yesterday.

**Comment by yichenroy** [comment]
Resent here: https://github.com/pyoo47/liferay-portal/pull/1244

**Pull request closed without merging**
