### PR TITLE
LRQA-46039 Record slave usage of builds

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-46039

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by lesliewong92** [comment]
@pyoo47 I didn't rename the method generateMetricLabels() other than moving it into the new StatsDMetricsUtil class. I forgot to ask about this when we talked. Let me know if you want to change it.

**Comment by lesliewong92** [comment]
ci:stop

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@lesliewong92 Unit test failure. Can you fix and resend?

**Comment by lesliewong92** [comment]
Fixed and resent at https://github.com/pyoo47/liferay-portal/pull/952

**Pull request closed without merging**
