### PR TITLE
LRCI-101 Retire previous builds that exceed a certain age

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-101

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@michaelhashimoto I tried putting https://github.com/pyoo47/liferay-portal/pull/1006 and https://github.com/pyoo47/liferay-portal/pull/1007 together but I ran into a merge conflict. Can you fix the issue and update this branch (*master-ci-101-1*)?

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/70760

**Pull request closed without merging**
