### PR TITLE
master-qa-18824-1

### PR DESCRIPTION
**Pull request by kevin-yen**
https://issues.liferay.com/browse/LRQA-18824

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest (Something bad got into upstream but it should be fixed now)

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Comment by kevin-yen** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/38958

**Pull request closed without merging**
