### PR TITLE
LRCI-1156 Add class SpiraCustomProperty to handle interaction with different Spira Artifacts

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1156

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@michaelhashimoto
What exactly is the string that is returned by `getType()` Is it a Spira keyword for the type of object? I'm asking because you can probably figure out the type by using `instanceof` in Java but if you need to pass the Spira keyword to Spira then this approach makes sense. I'm going to forward for now and we can make a followup change later if needed.

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
