### PR TITLE
LRCI-3875 Add a cron to archive old jobs

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://liferay.atlassian.net/browse/LRCI-3875

### CODE REVIEW

**Comment by pyoo47** [comment]
Failure is in `:portalYarnCheckFormat.`

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:stable

**Comment by pyoo47** [comment]
ci:forward:force

**Pull request closed without merging**
