### PR TITLE
LRQA-35073

### PR DESCRIPTION
**Pull request by cesar-polanco**
Modified to no longer use beanshell. Ticket available at https://issues.liferay.com/browse/LRQA-35073

### CODE REVIEW

**Comment by cesar-polanco** [comment]
ci:reopen

**Comment by cesar-polanco** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Comment by cesar-polanco** [comment]
ci:retest

**Comment by pyoo47** [comment]
Made a change and pushed to Cesar for testing.
https://github.com/cesar-polanco/liferay-portal/pull/8

**Pull request closed without merging**
