### PR TITLE
LRCI-1128 Add methods to integrate test case types into spira test cases

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1128

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to myself for forwarding to BChan
https://github.com/pyoo47/liferay-portal/pull/1265

@michaelhashimoto Please see my minor changes in https://github.com/pyoo47/liferay-portal/pull/1265/commits/1dd78983a2951d705f3f0fc9d9fd563fd378fa21

**Pull request closed without merging**
