### PR TITLE
LRCI-4268 Fix synchronization issue & jenkins pull request tester

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://liferay.atlassian.net/browse/LRCI-4268

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
