### PR TITLE
LRCI-1989 Add class to represent Testray Builds

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1989

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to myself with a small change for forwarding to BChan.
https://github.com/pyoo47/liferay-portal/pull/1693

@michaelhashimoto Please see https://github.com/pyoo47/liferay-portal/commit/beb939064a75f47e193427a1b816372bbeee5d16

**Pull request closed without merging**
