### PR TITLE
LRQA-34216 Subrepository mentions

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-34216

Examples of pulls of the mention working (see the very first comment):
https://github.com/liferay/liferay-portal/pull/1971

https://github.com/liferay/liferay-portal/pull/1968

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:stop
renamed one of the commits

**Comment by yichenroy** [comment]
ci:retest

**Comment by yichenroy** [comment]
ci:reopen

**Comment by yichenroy** [comment]
ci:retest
rebased, going to retest.

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/51951

**Pull request closed without merging**
