### PR TITLE
LRQA-42614 Use repository directory name instead of repository name in git working directory factory

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-42614

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/61676

@yichenroy Please see my changes in the pull request.

**Comment by pyoo47** [comment]
ci:stop

**Pull request closed without merging**
