### PR TITLE
LRQA-41694 Turn on modules compile and semantic versioning batches | 7.1.x

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-41694

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test

**Comment by pyoo47** [comment]
@lesliewong92 What do you make of this sf failure?
```
1: Property value 'modules/test/poshi-runner/poshi-runner/src/main/java/com/liferay/poshi/runner/util/GetterUtil.java' points to file that does not exist: ./modules/test/source-formatter.properties (SourceCheck:PropertiesSourceFormatterFileCheck)
```

**Comment by lesliewong92** [comment]
@pyoo47 This is because the poshi runner module does not even exist on this branch. I'll send a PR to remove that path from source-formatter.properties.

**Comment by lesliewong92** [comment]
Sent pull to fix this. See https://github.com/pyoo47/liferay-portal/pull/697.

**Comment by lesliewong92** [comment]
Closing. Will send again after changes made to jenkins results parser jar.

**Pull request closed without merging**
