### PR TITLE
LRQA-41001 Include service builder and allow specifying required junit tests that will always run in ci:test:relevant

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-41001

I tested these changes with a jenkins-results-parser.jar made from these changes in a pull to myself here:
https://github.com/yichenroy/liferay-portal/pull/58
same failure as an upstream build that hasn't finished running
https://test-1-1.liferay.com//userContent/jobs/test-portal-acceptance-upstream%28master%29/builds/3909/jenkins-report.html

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
Unique failure is the same as the upstream failure that ran around the same time (integration-mysql57-jdk8):
https://test-1-1.liferay.com//userContent/jobs/test-portal-acceptance-upstream%28master%29/builds/3911/jenkins-report.html

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/58928
https://github.com/brianchandotcom/liferay-portal-ee/pull/20256

**Pull request closed without merging**
