### PR TITLE
LRQA-46526 Fix failing Liferay Faces tests due to Out of Memory error

### PR DESCRIPTION
**Pull request by kevin-yen**
https://issues.liferay.com/browse/LRQA-46526

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by stiemannkj1** [comment]
@pyoo47, I'm not sure what these failures are or why these tests are marked relevant. If you look at the changes I've made, I only changed the "jsf-jdk8" test. And those changes passed in my original PR with `ci:test:jsf`: https://github.com/kevin-yen/liferay-portal-ee/pull/67#issuecomment-459536797

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/67503

**Comment by pyoo47** [comment]
@stiemannkj1 No worries. The test did not identify the failure as a unique failure meaning that the same failure happened in the the upstream acceptance test so I'm pretty sure it is not directly related to this pull request.

**Pull request closed without merging**
