### PR TITLE
LRQA-32925 Make semantic versioning failure message more concise

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-32925

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:stop

**Comment by yichenroy** [comment]
ci:retest

**Comment by yichenroy** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/49364

**Comment by yichenroy** [comment]
ci:reopen

**Pull request closed without merging**
