### PR TITLE
POSHI-50 Update multithreading logic

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-50

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
@pyoo47, I have some theories on this... but we can talk about it more tomorrow.

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
Sent back to Kenji for review/testing.
https://github.com/kenjiheigel/liferay-portal/pull/550

**Pull request closed without merging**
