### PR TITLE
LRCI-4138 Add ability to create a cron routine from the UI

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://liferay.atlassian.net/browse/LRCI-4138

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by pyoo47** [comment]
ci:test:stable:da0175e6eb9c61af012cedeaf57411a1c8933ebd

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/149280

**Pull request closed without merging**
