### PR TITLE
LRCI-4539 Fix rules that fail rule validation

### PR DESCRIPTION
**Pull request by brittneyq**
https://liferay.atlassian.net/browse/LRCI-4540

### CODE REVIEW

**Comment by brittneyq** [comment]
FYI @ealonso and @kresimir-coko, I removed some batch test names because there was no corresponding property in the respective test.properties file. If the batch names were kept there, it would have failed SF on CI/validation in a future relevant pull.

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
@AliciaGarciaGarcia, I added the missing playwright-js-tomcat90-mysql57-jdk8 to test.batch.names based on your change [here.](https://github.com/liferay/liferay-portal/commit/290432ab0e6f7f2d8f20c4edb6413c3d7dca01ff)

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
