### PR TITLE
LRQA-43676 Remove autobalance property for modules-unit-project-templates (master)

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-43676

Related:
https://github.com/pyoo47/liferay-portal-ee/pull/427 (7.1.x)
https://github.com/pyoo47/liferay-portal-ee/pull/428 (7.0.x)

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/63362

**Pull request closed without merging**
