### PR TITLE
POSHI-107 Add 'poshi-core' module

### PR DESCRIPTION
**Pull request by michaelhashimoto**
http://issues.liferay.com/browse/POSHI-107

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@michaelhashimoto Why the inclusion of LiferaySelenium.java? Is it supposed to act as a sort of sample file for an otherwise empty module?

**Comment by pyoo47** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
@pyoo47 - Yeah, it's just the first class to show what it'll eventually look like when all the other classes are included.

**Pull request closed without merging**
