### PR TITLE
LRCI-1115 Use already created spira builds when they are available

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1115

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
Added SF commit and sent to myself for forwarding
https://github.com/pyoo47/liferay-portal/pull/1234

**Comment by pyoo47** [comment]
ci:stop

**Pull request closed without merging**
