### PR TITLE
LRQA-30892 New jenkins report (reworked commits)

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-30892

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:retest

**Comment by pyoo47** [comment]
@yichenroy Merge conflict please resolve and resend.

**Comment by pyoo47** [comment]
@yichenroy Nevermind. I think i've got it

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/52756

**Pull request closed without merging**
