### PR TITLE
LRQA-39865 Add TestClassGroup class to split up plugins jobs

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-39865

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
@michaelhashimoto will create a "PluginGitWorkingDirectory" class and push to this pull request.

**Comment by michaelhashimoto** [comment]
ci:test:relevant

@pyoo47 - I made the updates you mentioned, thanks!

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/57040

@michaelhashimoto Please note my change in the pull request to BChan.

**Pull request closed without merging**
