### PR TITLE
LRCI-752 Fix off by one error with JenkinsResultsParserUtil#getRandomString

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-752

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/80565

**Comment by pyoo47** [comment]
@michaelhashimoto I thought of another potential issue so I added another commit and resent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/80608

**Pull request closed without merging**
