### PR TITLE
LRCI-1253 Fix upstream acceptance URLs

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-1253

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@kenjiheigel I think this change broke one of our unit tests.. Can you investigate?

**Comment by kenjiheigel** [comment]
Looking into it.

**Comment by kenjiheigel** [comment]
Resent: 
https://github.com/pyoo47/liferay-portal/pull/1294

**Pull request closed without merging**
