### PR TITLE
LRCI-3823 Add event handlers for GitHub messages

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://liferay.atlassian.net/browse/LRCI-3823

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:reevaluate:1277401_10780

**Pull request closed without merging**
