### PR TITLE
LRCI-1529 Use OrderedJSONObject in data generation

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-1529

I made additional renames from job -> build where applicable. According to Jenkins terminology (https://wiki.jenkins.io/display/jenkins/terminology), a job refers to a runnable task whereas the build is essentially an instance/result of a run of that job. I think our other usages follow that pattern already, so I adjusted my naming that didn't follow that. Additionally, JenkinsCohortJob can be kept as such, because the class should contain all the data that comes from one job, which has multiple builds, etc.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
