### PR TITLE
LRQA-44833 Add a simple test for LocalGitRepository objects

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-44833

@pyoo47 - After talking with @petershin we found a reduced version of the build.gradle that we can use.

I was thinking we might need to create a build-ext.gradle, like they do in [apio architecture](https://github.com/liferay/liferay-portal/tree/master/modules/apps/apio-architect).  However, Peter thinks we'll be okay with just putting it in build.gradle.

We'll see what BChan thinks.  Let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/65191

**Pull request closed without merging**
