### PR TITLE
LRCI-1064 Only remove quotes for gradle jvm arg on windows for poshi/gradle execute

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-1064
Will need back ports to 7.0.x, 7.1.x, and 7.2.x.

Tested here:
https://test-5-1.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/2672/jenkins-report.html (Linux on test-5-1)
https://test-2-1.liferay.com//userContent/jobs/test-portal-environment%28master%29/builds/922/jenkins-report.html (Windows on test-2-1)

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
@yichenroy, @pyoo47, this has been failing quite a few QA tests the past few days. I know Roy tested this last Fri, so I'm going to send this up to BChan with the backports.

**Comment by kenjiheigel** [comment]
Sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/85629
https://github.com/brianchandotcom/liferay-portal-ee/pull/29300 (7.2.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/29301 (7.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/29302 (7.0.x)

**Comment by yichenroy** [comment]
@kenjiheigel got it, thanks!

**Pull request closed without merging**
