### PR TITLE
LRCI-3803 Fix caching for related entities that are managed by Entity repositories

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://liferay.atlassian.net/browse/LRCI-3803

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/141268

**Pull request closed without merging**
