### PR TITLE
LRCI-311 Print liferay log when starting app servers

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-311

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@michaelhashimoto I'm going to forward this but I'm not sure if you've taken into account that "tail -f" will never exit. tail does not know when the process that is updating the text file it is tailing has exited. It simply watches the file forever and prints any new lines that get added to it by any process to standard out.

**Comment by pyoo47** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
@pyoo47 - You are right, I just checked the servers that are running these processes and they are still open.

**Pull request closed without merging**
