### PR TITLE
LRQA-41710 Remove unneccessary exclusion rules as module doesn't exist on branch

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/LRQA-41710

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by lesliewong92** [comment]
ci:reopen

**Comment by lesliewong92** [comment]
@pyoo47 Poshi Runner SF error is now removed.

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/60433

**Pull request closed without merging**
