### PR TITLE
POSHI-107 Move PropsUtil into 'poshi-core' to maintain history

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/POSHI-107

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@michaelhashimoto I think this means we aren't allowed to create a module dependency? Maybe Peter Shin can help resolve this one?

```
junit.framework.AssertionFailedError: Artifact dependency {compileInclude group: "com.liferay", name: "com.liferay.poshi.core", version: "1.0.1"} in modules/test/poshi/poshi-runner/build.gradle not permitted on master branch. Use a project dependency instead.
```

**Comment by michaelhashimoto** [comment]
@pyoo47 - I messaged Peter about it, I'll make the change after he gets back to me.

**Comment by michaelhashimoto** [comment]
Peter Shin sent a pull to allow this change to happen here:
https://github.com/petershin/liferay-portal/pull/1197

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Pull request closed without merging**
