### PR TITLE
LRCI-863 Test class group should take build profile into account (resend)

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-863

Tested here:
- dxp pr: 
https://test-5-2.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/536/jenkins-report.html
- dxp acceptance-upstream: 
https://test-5-2.liferay.com//userContent/jobs/test-portal-acceptance-upstream-dxp%28master%29/builds/3/jenkins-report.html
- portal pr: 
https://test-5-2.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/535/jenkins-report.html
- portal acceptance-upstream: 
https://test-5-2.liferay.com//userContent/jobs/test-portal-acceptance-upstream%28master%29/builds/17/jenkins-report.html

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:relevant

Unrelated failure: 
```
[beanshell] Unable to execute bash commands retrying... 
[beanshell] java.util.concurrent.TimeoutException: Timeout occurred while executing Bash commands: [git ls-remote -h git@github.com:liferay/liferay-portal-ee.git 7.0.x]
```

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/82291

**Comment by pyoo47** [comment]
@yichenroy Please see my changes in the pull request.
https://github.com/brianchandotcom/liferay-portal/pull/82291

**Pull request closed without merging**
