### PR TITLE
LRCI-1711 Add ci:test:relevant chart and data into CI System Status Report

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-1711

The additional changes will look like this: 
image

The frontend changes will be sent in liferay-jenkins-ee once a new jar is published.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by pyoo47** [comment]
This looks really good. I'd just like to move some of the constants into liferay-jenkins-ee properties. Specifically, I'd like to make changes to something resembling this:

```
CISystemStatusReportUtil._DAYS_AGO -> liferay-jenkins-ee/commands/build.properties#ci.system.status.report.history.length

CISystemStatusReportUtil._LIFERAY_DXP_73_PULL_REQUEST_RELEVANT_SUITE_RELEASE_ID -> liferay-jenkins-ee/commands/build.properties#ci.system.status.report.dxp.suite.release.id[relevant][7.3]

CISystemStatusReportUtil._LIFERAY_DXP_PROJECT_ID-> liferay-jenkins-ee/commands/build.properties#spira.project.id[dxp]
```

If this doesn't make sense, we can talk about this directly.. The names also are just suggestions. _DAYS_AGO is definitely too vague.

**Comment by kenjiheigel** [comment]
Oooh. Gotcha. I can make those changes as well as go through and see what else might make sense as build.properties and send the liferay-jenkins-ee side changes for that.

**Comment by kenjiheigel** [comment]
Properties sent here: 
https://github.com/pyoo47/liferay-jenkins-ee/pull/1685/

**Pull request closed without merging**
