### PR TITLE
LRQA-32801-1 Readable poshi translator: Add basic support for 'for' loops and conditionals

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-32801

### CODE REVIEW

**Comment by kenjiheigel** [comment]
#### Changes in this pull: 
* Trim strings where possible
* Uncouple logic - split the readable blocks into a list, then parse through that list instead of line by line.
* Add support for _for_ tags
* Add basic support (no nesting or logical operators) for _if, then, else, isset, equals, condition_ tags. 

#### Translation status
On master:
```
1163 / 2135 (54%) test commands were successfully translated
11 / 2135 test commands fail due to setup failures
1402 / 2135 test commands fail due to teardown failures
92 / 337 (27%) test files were successfully translated with 157 tests
Test commands that fail two way conversion: 428
```
With this pull: 
```
1414 / 2135 (66%) test commands were successfully translated
8 / 2135 test commands fail due to setup failures
108 / 2135 test commands fail due to teardown failures
182 / 337 (54%) test files were successfully translated with 520 tests
Test commands that fail two way conversion: 177
```

**Comment by pyoo47** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/50319

**Pull request closed without merging**
