### PR TITLE
LRCI-1447 Add JenkinsResultsParserUtil#executeBashService for app server starts

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1447

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
I made some changes and pushed to myself for forwarding.
https://github.com/pyoo47/liferay-portal/pull/1439

**Pull request closed without merging**
