### PR TITLE
LRCI-1211

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-1211

@pyoo47, let me know if this is ok and if you have any suggestions. If it's ok, I can send this and backports on Monday

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
@kenjiheigel This looks good to me. Go ahead and send in with backports. Thanks!

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@kenjiheigel Not sure what caused all the failures.. Seems like a portal startup issue. The previous test from Friday seemed a lot better. Maybe there's a portal startup issue in upstream? Although.. I checked the most recent master stable builds and they seem OK.

**Comment by kenjiheigel** [comment]
@pyoo47, seems odd. I'll do some more investigating.

**Pull request closed without merging**
