### PR TITLE
LRCI-2036 Generate data for CI status report's new PR section

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-2036
https://issues.liferay.com/browse/LRCI-2039
https://issues.liferay.com/browse/LRCI-2040
https://issues.liferay.com/browse/LRCI-2050

Did some logic reorgs. In JenkinsCohort.JenkinsCohortJob, instead of storing build counters, in addition to build URLs, we can store maps of queued build json objects. This will give us lots of information from minimal api calls. 

Additionally, I added the duration data into the LRCI-2039 commits. LRCI-2050 addresses potential memory issues, and was exposed by one of the tests due to changes I made.  

image

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by pyoo47** [comment]
@kenjiheigel I've tried running this unit test locally without any problems. My memory settings are probably not the same though. I'm wondering if we need to increase the heapsize? The files you added to liferay-jenkins-results-parser-samples-ee don't seem to be very big or very many so it's hard to understand why the memory footprint would have gone up. Any ideas?

**Comment by kenjiheigel** [comment]
@pyoo47, not sure. I'll investigate this more today

**Comment by kenjiheigel** [comment]
@pyoo47 , I queued another pull for this on test-5-1: http://test-5-1/job/test-portal-acceptance-pullrequest(master)/3994. It will fail with the LoadBalancerTest failure (cause I changed something again), but I want to see that the other issues have been fixed. 

If these changes look good, you can merge https://github.com/pyoo47/liferay-jenkins-results-parser-samples-ee/pull/23, then cache jenkins, then retrigger the build again.

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
