### PR TITLE
LRCI-4461 Invoke batches that don't require the portal bundle first

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://liferay.atlassian.net/browse/LRCI-4461

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@kenjiheigel will resend as two separate pull requests

**Comment by kenjiheigel** [comment]
Resent here: 
https://github.com/kenjiheigel/liferay-portal/pull/1731
https://github.com/pyoo47/liferay-portal/pull/3414

**Pull request closed without merging**
