### PR TITLE
POSHI-71 Ensure clean browser session for Internet Explorer driver

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-71

@yichenroy, @kenduenwald

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
@john-co fyi.

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

Had to fix a typo. Already aborted the other one that got queued.

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
