### PR TITLE
LRCI-1990 Add class to represent testray runs

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1990

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@michaelhashimoto I think ci:reevaluate may have worked here..

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
