### PR TITLE
LRCI-70 Add simple methods to configure GitHub SSH on a slave

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-70

The final groovy script for [LRCI-71](https://issues.liferay.com/browse/LRCI-71) will likely look something like this:
<pre><code>import com.liferay.jenkins.results.parser.JenkinsResultsParserUtil

JenkinsResultsParserUtil.writeSshIdRsa(System.getenv("ID_RSA"));

JenkinsResultsParserUtil.writeSshKnownHosts(System.getenv("KNOWN_HOSTS"));</code></pre>

Let me know what you think.

Thanks!

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/69561

@michaelhashimoto Please see my changes in the pull request

**Pull request closed without merging**
