### PR TITLE
POSHI-108 Simplify BaseWebDriverImpl.clickAt

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-108

@Tim-Cao, I added the 'scrollIntoView' back in. This logic is there because in some cases a web element would not be clickable because it was not viewable in the browser window. I'm adding it back in by default as a safeguard, which is how it previously functioned.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Thanks. I forgot that but it was in my mind.

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
