### PR TITLE
LRCI-2097 Streamline portal-fixpack-release and add gauntlet-bucket test suite

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-2097

Tested here:
gauntlet-bucket (master):
https://test-1-17.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7456/jenkins-report.html

portal-fixpack-release (7.3.x):
https://test-1-1.liferay.com//userContent/jobs/test-portal-fixpack-release/builds/801/jenkins-report.html

Please backport to `7.3.x` (clean cherry-pick)

I'll also prepare and send in backport pulls for 7.0.x, 7.1.x, 7.2.x.

cc @brianwulbern

### CODE REVIEW

**Comment by brianwulbern** [comment]
Hi guys, @LeventeFarkasLR, @MichaelPrigge, @adambalazs-lr, @CsabaTurcsan, 

After this change goes in, we'll want to change our HU bot to trigger gauntlets using a ci test `gauntlet-bucket` - it will run fewer test batches, yielding faster results, all while keeping the same level of valuable information we need to catch blockers and other regressions before customers do.

We're working with Engineering and Support to further iron out the process and really maximize the value returned in each part of our enterprise testing process.  Stay tuned!

cc @yunlinsun @reizero00

**Comment by brianwulbern** [comment]
Thanks, @yichenroy!

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
@LeventeFarkasLR, @MichaelPrigge, @adambalazs-lr, @CsabaTurcsan, @brianwulbern 
FYI BChan has merged this pull request.

**Pull request closed without merging**
