### PR TITLE
LRCI-3823 Add GitHub proxy reference & add ability to update the upstream branch on pushes

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://liferay.atlassian.net/browse/LRCI-3823

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
cI:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:stable

**Comment by pyoo47** [comment]
ci:forward:force

**Comment by pyoo47** [comment]
@michaelhashimoto You probably don't want to use the proxy when you are only downloading data from GitHub. Those kinds of requests can be processed by GitHub in parallel. It's just the ones where you are making updates to GitHub that you need to run through the proxy.

**Pull request closed without merging**
