### PR TITLE
LRQA-44623 Add validation for build parameters to ensure correct usage

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-44623

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@michaelhashimoto Shouldn't validateBuildParameters() return a value that indicates whether or not validation was successful? Looking at the code, it seems like the build description gets updated with all of the failure messages but nothing will prevent the top level build runner from moving ahead with the build.

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/64841

**Pull request closed without merging**
