### PR TITLE
LRQA-32923 Make source format failure message more accurate

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-32923

### CODE REVIEW

**Comment by pyoo47** [comment]
@yichenroy Looks like one of the github message unit tests is failing. I'm guessing the change you made has altered the github message that is generated so that it doesn't match the expected_message.html anymore. You can regenerate the expected_message.html by deleting the file and running the test again (gradlew test).

**Comment by yichenroy** [comment]
ci:reopen

**Comment by yichenroy** [comment]
ci:retest

**Comment by yichenroy** [comment]
ci:stop

**Comment by yichenroy** [comment]
ci:retest

**Comment by yichenroy** [comment]
I found some issues with using the new start and end tokens, will be looking into fixing it.

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Comment by yichenroy** [comment]
I fixed the issue, and the newly generated expected_message.html will also display the more accurate SF failure snippet (contrary to the snippet just disappearing from expected_message.html altogether).

**Comment by yichenroy** [comment]
ci:retest

**Comment by yichenroy** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/49428

**Pull request closed without merging**
