### PR TITLE
LRQA-46764 Fix jenkins report when build is completed

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-46746

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/68721

**Comment by pyoo47** [comment]
@yichenroy @lesliewong92 Please see my changes in the pull request.

**Pull request closed without merging**
