### PR TITLE
LRCI-1881 Fix concurrency issue & tck failures

### PR DESCRIPTION
**Pull request by michaelhashimoto**
http://issues.liferay.com/browse/LRCI-1881

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
Pushed to myself for forwarding
@michaelhashimoto Please see my small change https://github.com/pyoo47/liferay-portal/pull/1610/commits/3f34bbce99e1a0183b59fb51b298f91f9218003c

**Pull request closed without merging**
