### PR TITLE
master-qa-19646

### PR DESCRIPTION
**Pull request by kevin-yen**
https://issues.liferay.com/browse/LRQA-19646

### CODE REVIEW

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/39051

**Comment by pyoo47** [comment]
Reopening this pull request so I will remember to follow up with Kevin about Hashi's comment in my pull request to Brian (which I've closed).

**Comment by kevin-yen** [comment]
ci:retest

**Comment by kevin-yen** [comment]
ci:retest

**Comment by kevin-yen** [comment]
33968300cf6052dd0a58fc0d9b3ba966c9526295

**Comment by kevin-yen** [comment]
ci:retest:33968300cf6052dd0a58fc0d9b3ba966c9526295

**Comment by kevin-yen** [comment]
ci:retest

**Comment by kevin-yen** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/39115

**Pull request closed without merging**
