### PR TITLE
LRCI-618 Add ability to find the dist bundles build url

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-618

This is related to this jenkins pull:
https://github.com/pyoo47/liferay-jenkins-ee/pull/1180

If we change the properties names, we'll just need to change it in both of these places.

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
I made some modifications and sent a pull request back to Hashi for review and retesting.
https://github.com/michaelhashimoto/liferay-portal/pull/1310

**Pull request closed without merging**
