### PR TITLE
LRQA-43732 Fetch cached branches from GitHub Dev if SHA is not available

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-43732

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/63808

**Comment by pyoo47** [comment]
@michaelhashimoto Please see my changes in the pull request to BChan.

**Pull request closed without merging**
