### PR TITLE
LRQA-45288 We should avoid closing pulls if they are not on the list

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-45288

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/65853

@michaelhashimoto I think we ought to reduce the amount of duplicate code in AutoCloseUtil. Specifically, I think that autoCloseOnCriticalBatchFailures() and autoCloseOnCriticalTestFailures() ought to call autoClose(). Can you send a follow up pull request to do that? Let me know if you have questions.

**Comment by michaelhashimoto** [comment]
@pyoo47 - Okay, I'll look into it. Thanks!

**Pull request closed without merging**
