### PR TITLE
POSHI-92 Poshi cannot type some special characters on Safari

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-92

This issue ended up in limbo because of additional discussion. I'm going keep the tabbing functionality the same. If that behavior should change, then it can be addressed in another ticket. This fix will at least fix the issue that was reported in POSHI-92 and simplifies existing logic

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Merge conflict. will fix and restart test.

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
