### PR TITLE
POSHI-60 Add additional validation messaging to PQL query error logic

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-60

@michaelhashimoto, @yichenroy

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
Forgot one thing.

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by pyoo47** [comment]
ci:test:relevant:nocompile

**Comment by pyoo47** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
ci:test:poshi-gauntlet:nocompile

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
