### PR TITLE
LRCI-1351 Add test batches, properties, and suites for Ubuntu 14, 16, and 18

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-1351

Tested here:
Ubuntu 14:
https://test-5-1.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/3384/jenkins-report.html

Ubuntu 16:
https://test-5-1.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/3385/jenkins-report.html

Ubuntu 18:
https://test-5-1.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/3386/jenkins-report.html

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:sf

I applied a SF commit, retesting.

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
