### PR TITLE
LRCI-3246 Account for the new JUnit XML format if available

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-3246

### CODE REVIEW

**Comment by pyoo47** [comment]
@michaelhashimoto Wouldn't this be easier if you parse the XML using `Dom4JUtil.parse()` first, and then process the XML Elements? I'm concerned that this implementation is very brittle. Maybe there's a reason why you are trying to parse the XML as raw text but I'm just not getting it?

**Comment by michaelhashimoto** [comment]
@pyoo47 - The reason I had to do this is because when I tried to parse the XML file it threw this error:
<pre>xception in thread "main" org.dom4j.DocumentException: arraycopy: last destination index 3145 out of bounds for char[2049]
	at org.dom4j.io.SAXReader.read(SAXReader.java:513)
	at org.dom4j.io.SAXReader.read(SAXReader.java:408)
	at com.liferay.jenkins.results.parser.Dom4JUtil.parse(Dom4JUtil.java:280)
	at com.liferay.jenkins.results.parser.testray.DXPCloudClientTestrayImporter.main(DXPCloudClientTestrayImporter.java:48)
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 3145 out of bounds for char[2049]
	at java.base/java.lang.System.arraycopy(Native Method)
	at org.gjt.xpp.impl.tokenizer.Tokenizer.next(Tokenizer.java:1274)
	at org.gjt.xpp.impl.pullparser.PullParser.next(PullParser.java:392)
	at org.gjt.xpp.sax2.Driver.parseSubTree(Driver.java:415)
	at org.gjt.xpp.sax2.Driver.parse(Driver.java:310)
	at org.dom4j.io.SAXReader.read(SAXReader.java:494)
	... 3 more</pre>

For some reason the parse is unable to read the CDATA parts of the file.  Maybe the better solution is to just fix the parser.  Let me know if you think that is a better idea.  Thanks!

**Comment by pyoo47** [comment]
Probably a dom4j bug. Maybe we can hack it by [parsing it to a w3c Document](https://howtodoinjava.com/java/xml/parse-string-to-xml-dom/) and then [convert to a dom4J Document.](https://stackoverflow.com/questions/53007791/converting-org-w3c-dom-element-to-org-dom4j-element)

**Comment by michaelhashimoto** [comment]
Hey @pyoo47, I checked it out today, it works!  I'll try using it more fully tomorrow.

Thanks!  This should be much cleaner! :D

**Pull request closed without merging**
