### PR TITLE
LRCI-380 Dynamically create & destroy database pods for Jenkins slaves

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-380

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:stop

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
This looks good. Please send to BChan along with all necessary backports.

**Comment by kenjiheigel** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/75202
https://github.com/brianchandotcom/liferay-portal-ee/pull/25231 (7.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/25232 (7.0.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/25233 (ee-6.2.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/25234 (ee-6.2.10)
https://github.com/brianchandotcom/liferay-portal-ee/pull/25235 (ee-6.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/25236 (ee-6.1.30

**Pull request closed without merging**
