### PR TITLE
master-qa-24891

### PR DESCRIPTION
**Pull request by kevin-yen**
https://issues.liferay.com/browse/LRQA-24891

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
@brianchiu Can you or someone from your team take a look at the postgresql failures in the PR Test? This is the pull that will turn on the postgresql upgrade test but there a several functional test failures that use postgresql.

**Comment by brianchiu** [comment]
@pyoo47 
I'll have to take a look.

The screenshots show the tests stuck on the terms of use page (as if it's a completely new user logging in), which means that either the database import failed or the upgrade failed in some way. =\

I looked through the database dumps and the 6.0 and 6.1 ones are fine, but for some reason the 6.2 one is bad. I'll regenerate the 6.2 one.

**Comment by pyoo47** [comment]
@brianchiu Thanks Brian. I'll refrain from pushing this to BChan until I hear back from you.

**Comment by brianchiu** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchiu** [comment]
@kevin-yen @pyoo47 
I'm trying it locally now. Will let you know.

**Comment by brianchiu** [comment]
@kevin-yen @pyoo47 
Something is wrong with the import. The legacy database isn't actually getting imported. This is why the failure occurs - because it tries to assert data that isn't there.

**Comment by kevin-yen** [comment]
ci:retest

**Comment by kevin-yen** [comment]
ci:retest

**Comment by kevin-yen** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/39915

**Pull request closed without merging**
