### PR TITLE
LRQA-33269 Add modules-comp, sem ver, startup failures sample to BuildTest (and expected_message.html)

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-33269

This has to be merged first:
https://github.com/pyoo47/liferay-jenkins-results-parser-samples-ee/pull/7

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by yichenroy** [comment]
ci:reopen

**Comment by yichenroy** [comment]
ci:retest

**Comment by pyoo47** [comment]
@yichenroy When I run the unit tests locally, it hangs. I can't tell which test it hangs on but I suspect that's why we are seeing aborts. Can you investigate? If you add some System.out.println's you should be able to determine where it hangs.

**Comment by pyoo47** [comment]
@yichenroy Actually it didn't hang. It just took an unusually long time to complete. I'll reopen and retest and see what happens.

**Comment by pyoo47** [comment]
ci:retest

**Comment by yichenroy** [comment]
I ran the unit tests locally and nothing was aborted
gradlew test  took about 3 minutes to complete and reach BUILD SUCCESSFUL 

Will have to investigate further when the retest finishes.

**Comment by yichenroy** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/50282

@yichenroy Please note the change I made. https://github.com/brianchandotcom/liferay-portal/pull/50282/commits/bf46492816cdeda8427c7de8a0b1ff93bdc0c891

**Pull request closed without merging**
