### PR TITLE
LRCI-1447 Allow for running batch commands as a service

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1447

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
