### PR TITLE
LRQA-45826 Fix the null pointer when checking out an upstream branch & shorten timeout to 15 minutes

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-45826

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/66605

**Pull request closed without merging**
