### PR TITLE
LRQA-40204

### PR DESCRIPTION
**Pull request by cesar-polanco**
Adding an AntUtil class and abstracting out the "runTask" function that is used in several beanshell tags within liferay-jenkins-ee.

When this jar is published, it will facilitate a re-sending of LRQA-39312.

This should address https://issues.liferay.com/browse/LRQA-40204

### CODE REVIEW

**Comment by cesar-polanco** [comment]
ci:test:relevant

**Comment by cesar-polanco** [comment]
ci:reopen

**Comment by cesar-polanco** [comment]
ci:test:relevant

**Comment by cesar-polanco** [comment]
ci:stop

**Comment by cesar-polanco** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/57365

@cesar-polanco Please note that I changed the name of the method to `callMacrodef()`

**Pull request closed without merging**
