### PR TITLE
LRQA-47858, LRCI-83 Add PMD and Jenkins regen failure message generators

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-47858
https://issues.liferay.com/browse/LRCI-83

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by jpince** [comment]
image
@pyoo47

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/70500

**Pull request closed without merging**
