### PR TITLE
LRQA-33105 Add portal license batch test to pullrequest tester

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-33276

This cannot be tested with the pull request tester until the following has been merged into upstream (relies on jenkins-ee to setup the test environment)
pyoo47/liferay-jenkins-ee#487

The new portal license batch test has passed the pullrequest tester using (build-with-parameters) on jenkins to point to my jenkins branch:
yichenroy#13

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by yichenroy** [comment]
ci:reopen

**Comment by yichenroy** [comment]
ci:retest

**Comment by yichenroy** [comment]
Will look into the issue and retest.

**Comment by pyoo47** [comment]
@yichenroy Please resend after you've figured out what's gone wrong here. Thanks.

**Pull request closed without merging**
