### PR TITLE
LRCI-1991 Add classes for testray case objects

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1991

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed back to Hashi for his review and forwarding to BChan
https://github.com/michaelhashimoto/liferay-portal/pull/1755

@michaelhashimoto Please see https://github.com/michaelhashimoto/liferay-portal/pull/1755/commits/794fd7250764cf6a9f00e2c2ea217b1fac09eef7

**Pull request closed without merging**
