### PR TITLE
LRQA-34578 Modify poshi file intake to read per resource

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-34578

### CODE REVIEW

**Comment by pyoo47** [comment]
@lesliewong92 I suspect that these failures have something to do with this pull? Can you take a look?

**Comment by lesliewong92** [comment]
ci:retest

**Comment by lesliewong92** [comment]
ci:reopen

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/51196

**Pull request closed without merging**
