### PR TITLE
LRQA-41724 Only return list of all modules if test suite is 'default'

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-41724

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by lesliewong92** [comment]
ci:reopen

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/60458

**Pull request closed without merging**
