### PR TITLE
Lrqa 33616

### PR DESCRIPTION
**Pull request by cesar-polanco**
This pull request addresses: https://issues.liferay.com/browse/LRQA-33616

### CODE REVIEW

**Comment by cesar-polanco** [comment]
ci:reopen

**Comment by cesar-polanco** [comment]
ci:stop

**Comment by cesar-polanco** [comment]
ci:retest

**Comment by cesar-polanco** [comment]
ci:stop

**Comment by cesar-polanco** [comment]
ci:retest

**Comment by cesar-polanco** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/50174

**Pull request closed without merging**
