### PR TITLE
LRQA-40085 Change the way batches add autobalance tests (master)

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-40085

Will need a jar published.

This is rebased on top of Hashi's pull to add reading nested properties:  https://github.com/pyoo47/liferay-portal/pull/615

Backported test.properties change to 7.0.x and sent a pull here:
https://github.com/pyoo47/liferay-portal-ee/pull/340

cc
@michaelhashimoto

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:reopen

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/57380

**Pull request closed without merging**
