### PR TITLE
LRQA-39077 Make labels and pullrequests more public, and update github message

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-39077

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/56202

**Pull request closed without merging**
