### PR TITLE
LRCI-1136 Add allowed sender names property to ci.properties

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-1136

@pyoo47 This will automatically allow webhook to reject pull requests sent to BChan on master, I'm working on the webhook changes for the message to print when rejected on master.

EDIT: after talking to Peter we've decided to hardcode this behavior in the webhook for now so we can control when this goes into effect without relying on the master stable job to sync.

This is a long-term approach that will be explored later, leaving pr open for now.

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant:nocompile

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
