### PR TITLE
POSHI-35, POSHI-58, POSHI-30, POSHI-57

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/POSHI-35
https://issues.liferay.com/browse/POSHI-58
https://issues.liferay.com/browse/POSHI-30
https://issues.liferay.com/browse/POSHI-57

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
ci:forward

please

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by kenjiheigel** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
🎉🚀🥇

**Pull request closed without merging**
