### PR TITLE
LRCI-3940 output messages to catch Testray result and log mismatch

### PR DESCRIPTION
**Pull request by CharlotteFrancis**
https://liferay.atlassian.net/browse/LRCI-3940

### CODE REVIEW

**Comment by CharlotteFrancis** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by CharlotteFrancis** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
Pushed to myself with a small change
https://github.com/pyoo47/liferay-portal/pull/3144

**Pull request closed without merging**
