### PR TITLE
LRQA-43448 Generate csv report for junit backend tests

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-43448

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:reopen

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
Sent back to Roy with a small change for retesting.

**Pull request closed without merging**
