### PR TITLE
LRCI-3258 upgrade db2 version to 11.5.7

### PR DESCRIPTION
**Pull request by CharlotteFrancis**
https://issues.liferay.com/browse/LRCI-3258

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by CharlotteFrancis** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
Forwarded to myself with SF fix
https://github.com/pyoo47/liferay-portal/pull/2533

**Pull request closed without merging**
