### PR TITLE
LRCI-3746 Validate bnd file and project name

### PR DESCRIPTION
**Pull request by brittneyq**
https://liferay.atlassian.net/browse/LRCI-3746 

Hi Peter, going to send along validating the bnd and project name commit while I figure out why project-templates isn't being generated with format-source-bnd. Thanks.

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:reevaluate:1287401_7352

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:stable

**Comment by pyoo47** [comment]
ci:forward:force

**Pull request closed without merging**
