### PR TITLE
LRCI-3706 Apply the Retryable class to the DALO classes to avoid redundancy

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://liferay.atlassian.net/browse/LRCI-3706

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by pyoo47** [comment]
ci:forward:force

**Pull request closed without merging**
