### PR TITLE
POSHI-110 Ocular implementation | POSHI-130 Clean up BaseWebDriverImpl constructor

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-110
https://issues.liferay.com/browse/POSHI-130

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to myself with some minor changes for forwarding to BChan
https://github.com/pyoo47/liferay-portal/pull/1567

**Pull request closed without merging**
