### PR TITLE
LRQA-38683 Create a more useful Message Generator for SF errors

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-38683

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:reopen

portal-smoke failure unrelated to this pull.

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/57205

**Comment by pyoo47** [comment]
@yichenroy Please see my changes in the pull request to BChan

**Pull request closed without merging**
