### PR TITLE
LPD-23945, LRCI-4187 | Add playwright test batch in release tester 

### PR DESCRIPTION
**Pull request by pyoo47**
https://liferay.atlassian.net/browse/LPD-23945
https://liferay.atlassian.net/browse/LRCI-4187

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward:force

**Comment by john-co** [comment]
ci:forward:force

**Comment by pyoo47** [comment]
ci:forward:forceOn May 2, 2024, at 2:03 PM, Liferay Continuous Integration ***@***.***> wrote:﻿
Jenkins Build:test-portal-acceptance-pullrequest(master)#10577Jenkins Report:jenkins-report.htmlJenkins Suite:stablePull Request:pyoo47#3196Testray Routine:EE Pull RequestTestray Build:[master] ci:test:stable - pyoo47 > pyoo47 - PR#3196 - 2024-05-02[12:31:26]Testray Build ID:2565243157Testray Importer:publish-testray-report#21811

**Pull request closed without merging**
