### PR TITLE
LRCI-2753 Add support for IBM db2 Docker image

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRCI-2753

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant: ce86c15de5f8a1308c17ebdf6a6096

**Comment by pyoo47** [comment]
ci:test:relevant:184419ab527ad5b0ce42d4bd72bb59b5ca635328

**Comment by pyoo47** [comment]
ci:reevaluate:1287401_2706

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:reevaluate:1257401_2270

**Comment by CharlotteFrancis** [comment]
ci:test:relevant

**Pull request closed without merging**
