### PR TITLE
LRQA-31410 Autoclose GitHub reports have invalid Test Report URLs

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-31410

@pyoo47, @michaelhashimoto, I tested this locally and generated this output: https://gist.github.com/kenjiheigel/14f58030bb214e2308e799a0733a1945. This should fix generated links for integration tests

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/47804

**Pull request closed without merging**
