### PR TITLE
LRQA-33105 Add portal license batch test to pull request tester

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-33276

The file "masterList" is a placeholder for an official list that should be provided by Amos Fong
Source:
https://issues.liferay.com/browse/LRQA-33105

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:stop

**Comment by yichenroy** [comment]
"dist.type not set" error persists, will resend after more testing.
Closing pull request.

**Comment by yichenroy** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to Amos Fong
https://github.com/amosfong/liferay-portal/pull/29

**Comment by pyoo47** [comment]
@yichenroy Please see my changes in the pull to Amos.

**Pull request closed without merging**
