### PR TITLE
LRCI-2939 Add Amazon Linux 2 batches

### PR DESCRIPTION
**Pull request by brittneyq**
https://issues.liferay.com/browse/LRCI-2939

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:reevaluate:1267401_4211

**Comment by pyoo47** [comment]
ci:test:relevent:nocompile

**Comment by brittneyq** [comment]
ci:test:relevant:nocompile

**Comment by brittneyq** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
