### PR TITLE
LRQA-46864 Read in legacy repo test.properties instead of parsing Poshi XML

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-46864

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
@pyoo47, this should be a pretty isolated change btw, as these legacy classes are only used in beanshell for the legacy-database-dump job. Tested the jar here:
https://test-5-1.liferay.com//userContent/jobs/legacy-database-dump/builds/156/jenkins-report.html (failures are unrelated)

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/68507

**Comment by pyoo47** [comment]
@kenjiheigel Please see my changes in the pull request

**Pull request closed without merging**
