### PR TITLE
LRQA-28184 Add methods to get text from Ace Editor

### PR DESCRIPTION
**Pull request by lesliewong92**
http://issues.liferay.com/browse/LRQA-28184

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:reopen

**Comment by lesliewong92** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/43841

**Pull request closed without merging**
