### PR TITLE
LRCI-1128 Add methods to integrate test case types into spira test cases

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRCI-1128

Please publish after merging

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:close

Pushed to Peter.
https://github.com/pyoo47/liferay-portal/pull/1266

**Pull request closed without merging**
