### PR TITLE
LRQA-27233 Remove unnecessary helper methods since logic is in BaseWebDriverImpl

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-27233

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Tested with a local release here (the blogs failures are unrelated): 
https://github.com/kenjiheigel/liferay-portal/pull/302

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by kenjiheigel** [comment]
SF failure is not related.

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/44468

**Pull request closed without merging**
