### PR TITLE
LRCI-1128 Add class for handling test case types in spira

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1128

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Pushed to myself for forwarding
https://github.com/pyoo47/liferay-portal/pull/1259

**Pull request closed without merging**
