### PR TITLE
LRCI-3808 Modify release files for quarterly release

### PR DESCRIPTION
**Pull request by brittneyq**
https://liferay.atlassian.net/browse/LRCI-3808

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:forward

**Comment by brittneyq** [comment]
ci:test:stable 

Failures look unrelated, going to run stable again.

**Comment by pyoo47** [comment]
Pushed to myself with a change
https://github.com/pyoo47/liferay-portal/pull/2814

**Pull request closed without merging**
