### PR TITLE
LRCI-1586 Add MariaDB 10.4 test batches

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-1586

Please backport to 7.2.x

Tested here:
https://github.com/yichenroy/liferay-portal/pull/497

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@yichenroy Do we need to do any backporting for this?

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
