### PR TITLE
LRCI-828, LRCI-842, LRCI-853 Docker db fixes

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-828
https://issues.liferay.com/browse/LRCI-842
https://issues.liferay.com/browse/LRCI-853

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
Looks good. Please send to BChan along with backports.

**Comment by kenjiheigel** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/82180

**Pull request closed without merging**
