### PR TITLE
LRQA-41133

### PR DESCRIPTION
**Pull request by pyoo47**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
@peter-shin Do you know what is causing this SF failure? I'm seeing the same exception when I try to run SF locally.

**Comment by petershin** [comment]
@pyoo47 Try running the `compile` task instead of `setup-sdk` before running SF.  I think that will work.

**Comment by pyoo47** [comment]
ci:test:sf

**Pull request closed without merging**
