### PR TITLE
LRQA-36241 PR tester GitHub message updates

### PR DESCRIPTION
**Pull request by kenjiheigel**
[LRQA-36241](https://issues.liferay.com/browse/LRQA-36241) Clarify github message when there are only upstream failures and nothing unique
[LRQA-37192](https://issues.liferay.com/browse/LRQA-37192) Only show top level failure section if it's the only failure

#### Unique failure change: 
It got way to complicated trying to change the summary title. Just sending the basic change. It'll look like https://github.com/michaelhashimoto/liferay-portal/pull/1177#issuecomment-356479345 instead of https://github.com/brianchandotcom/liferay-portal/pull/54213#issuecomment-356430862

#### Top level failure change
Omitted top level portions are reflected in the expected_message.html files. Also note that RebaseErrorTopLEvelBuildTemplate.html doesn't need to be updated because for rebase errors, only the top level fails and no downstreams.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test

**Comment by kenjiheigel** [comment]
ci:stop

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci;retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/54331

**Pull request closed without merging**
